### ISSUE TITLE
Overseeable design for issue list

### ISSUE THREAD

**Issue by NPadrutt** [michelsalib/Gi7#62]
I suggest that we make some design changes for the issue list in order to improve the overview. For example let's only show one or two lines of the description.

The rest can be displayed after open the respective issue.

**Comment by RandomlyKnighted** [comment]
I agree, it seems kinda redundant to have an whole view for the issues if you can just read the full description on the issues pivot.

**Comment by RandomlyKnighted** [comment]
With just a quick glance into both the project code and the GitHub documentation I found the following:

In the GitHub documentation, if you go to the link found [here](https://api.github.com/repos/michelsalib/Gi7/issues) you will get the full list of issues being retrieved by the app when viewing the Gi7 repository. 

In the project, the RepositoryView.xaml uses the Paginated IssueListBox. This requests the data from the link above and from what I can tell in the emulator it is using the following data:

1. title
2. username of user who submitted the issue
3. date and time the issue was last updated (UTC time)
4. number of comments
5. body

We'd have to brake up the body text after so many characters or even after so many words. We seem to be averaging  8-9 words per line so if we wanted we could always cut it off after 18 words. We might can fix this in the Gi7.Client project by using the get accessor to trim the data before returning it.

**Comment by NPadrutt** [comment]
Is the wordwrap option elipsis not available? This would cut the text when there not enough space and mark it with a "..." at the end.

**Comment by RandomlyKnighted** [comment]
Thanks I'm still a bit new to all the XAML attributes so I wasn't aware of the TextTrimming attribute. All I had to do was give the TextBlock a fixed height and set the TextTrimming attribute.
